<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="stl" nsURI="http://www.example.org/stl" nsPrefix="stl">
  <eClassifiers xsi:type="ecore:EClass" name="ProductionLineModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemtypes" upperBound="-1"
        eType="#//ItemTypes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="area" lowerBound="1" upperBound="-1"
        eType="#//Area" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1"
        eType="#//Connectors" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Components" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slots" upperBound="-1"
        eType="#//Slots" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemTypes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Area">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Components" eOpposite="#//Components/area"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1"
        eType="#//Connectors" eOpposite="#//Connectors/area"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Components" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="area" lowerBound="1" eType="#//Area"
        eOpposite="#//Area/components"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="costs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" upperBound="-1"
        eType="#//Service" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connectors">
    <eStructuralFeatures xsi:type="ecore:EReference" name="area" lowerBound="1" eType="#//Area"
        eOpposite="#//Area/connectors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputslot" lowerBound="1"
        eType="#//InputSlot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputslot" lowerBound="1"
        eType="#//OutputSlot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemGenerator" eSuperTypes="#//Components">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputslot" lowerBound="1"
        eType="#//OutputSlot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemtypes" lowerBound="1"
        eType="#//ItemTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conveyor" eSuperTypes="#//Components">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputslot" lowerBound="1"
        eType="#//InputSlot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputslot" lowerBound="1"
        eType="#//OutputSlot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Turntable" eSuperTypes="#//Components">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputslot" lowerBound="1"
        upperBound="-1" eType="#//InputSlot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputslot" lowerBound="1"
        upperBound="-1" eType="#//OutputSlot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine" eSuperTypes="#//Components">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputslot" lowerBound="1"
        upperBound="-1" eType="#//InputSlot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputslot" lowerBound="1"
        upperBound="-1" eType="#//OutputSlot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Buffer" eSuperTypes="#//Components">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputslot" lowerBound="1"
        eType="#//InputSlot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputslot" lowerBound="1"
        eType="#//OutputSlot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductStore" eSuperTypes="#//Components">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputslot" lowerBound="1"
        eType="#//InputSlot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WasteStore" eSuperTypes="#//Components">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputslot" lowerBound="1"
        eType="#//InputSlot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slots" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputSlot" eSuperTypes="#//Slots">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredAsImput" lowerBound="1"
        eType="#//ItemTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputSlot" eSuperTypes="#//Slots">
    <eStructuralFeatures xsi:type="ecore:EReference" name="producedAsOutput" lowerBound="1"
        eType="#//ItemTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reliability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processingTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namedParameters" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
